### ISSUE TITLE
difficult measure

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#62]
f(x) * p(x) is a selling point, compared to doing intractable integrals in GPBQ

**status: high urgency**

**Comment by XingLLiu** [comment]
I tried gaussian prior p on f(x)/p(x), where f is the gaussian genz family and below are two plots after 300 iterations of BART with sequential design. My idea was that if the prior density mimic the target distribution (which it does in this case), this importance sampling might improve the performance. 

I tried two gaussian priors, one with sd=1 and the other with a sd engineered to resemble the "dispersion parameter" of f (which we chose to be dim^2/100). It appears that the difference in the convergence plots was not so obvious -- we have quicker convergence and slightly lower variance only when the prior sd is engineered. Gaussian prior with sd=1 is still quite flat because of the truncation (see plot 3), so the resulted samples do not show improvement over the uniform prior.


[sd_1.pdf](https://github.com/flaxter/BO-BART/files/4107440/sd_1.pdf)
[sd_engineered.pdf](https://github.com/flaxter/BO-BART/files/4107508/sd_engineered.pdf)
[priors.pdf](https://github.com/flaxter/BO-BART/files/4107567/priors.pdf)
